<a href="https://colab.research.google.com/github/ilmaazizah2/query/blob/master/Latian_Python_Application_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## `Pastikan klik 'File > Save a copy in Drive' sebelum memulai pengerjaan`

# Pengaplikasian Python dalam Data Analysis

## Tujuan

Setelah menyelesaikan lab ini, kamu akan mampu untuk:
*   Mengunggah dataset dengan `file.upload` dan mengunduh dataset dengan `file.download`
*   Pengelolaan data `date`
*   Penggunaan fungsi `pivot_table` & `groupby`
*   Membuat dan menggunakan fungsi sederhana pada `DataFrame`
*   Membuat visualisasi secara sederhana dengan menggunakan `plot`
*   Menjalankan SQL di Colab dengan `sqlite3`

In [1]:
#1
#Mengimpor Libraries
import pandas as pd
import numpy as np
from google.colab import files #unggah dan unduh file
import io #membaca data

In [2]:
#2
#Mengimpor dataset
URL = 'https://raw.githubusercontent.com/dataskillsboost/FinalProjectDA11/main/tokopaedi.csv'
df = pd.read_csv(URL)
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,subcategory,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## Mengunggah dan Menggunduh Dataset

In [3]:
#3
#Mengunggah dataset dengan upload file
unggah = files.upload()

Saving Canada.xlsx to Canada.xlsx

In [4]:
#4
#Membaca dataset
df_unggah = pd.read_excel('Canada.xlsx')
df_unggah

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,United Nations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Population Division,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Department of Economic and Social Affairs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,International Migration Flows to and from Sele...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,POP/DB/MIG/Flow/Rev.2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,December 2015 - Copyright © 2015 by United Nat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"Suggested citation: United Nations, Department...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,International Migration Flows to and from Sel...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Reporting country: Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Criterion: Citizenship,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Classification,NaN,Regional aggregates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Type,Coverage,AreaName,RegName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012.0,2013.0
20,Immigrants,Citizens,Northern America,Northern America,..,..,..,..,..,..,...,..,..,..,..,..,..,..,1,1.0,NaN
21,Immigrants,Foreigners,Africa,Eastern Africa,1471,1641,1426,1094,1187,1134,...,7726,7083,6750,6669,6705,6922,8591,8956,8846.0,NaN
22,Immigrants,Foreigners,Africa,Middle Africa,33,27,44,32,42,30,...,2452,2802,2834,2951,3034,3255,3369,3146,4602.0,NaN
23,Immigrants,Foreigners,Africa,Northern Africa,1100,1268,1348,936,842,840,...,12478,11323,12705,11750,13456,16320,19271,15712,15453.0,NaN
24,Immigrants,Foreigners,Africa,Southern Africa,1041,1126,791,387,297,327,...,1203,1012,1148,1230,1184,1235,1306,1049,1348.0,NaN
25,Immigrants,Foreigners,Africa,Western Africa,306,301,210,222,271,319,...,4333,5303,5751,5684,5511,6802,8355,6578,7834.0,NaN
26,Immigrants,Foreigners,Africa Total,NaN,3951,4363,3819,2671,2639,2650,...,28192,27523,29188,28284,29890,34534,40892,35441,38083.0,NaN
27,Immigrants,Foreigners,Asia,Central Asia,..,..,..,..,..,..,...,995,1134,903,936,805,962,905,769,1029.0,NaN
28,Immigrants,Foreigners,Asia,Eastern Asia,6836,8895,5481,3254,2624,2979,...,43550,50306,41763,35591,39602,37497,37954,35159,40449.0,NaN
29,Immigrants,Foreigners,Asia,South-Eastern Asia,8693,9191,9022,8845,12161,9787,...,18056,22809,25105,27256,30614,34166,44199,40494,37695.0,NaN
30,Immigrants,Foreigners,Asia,Southern Asia,11315,11566,11591,10157,9607,7654,...,58521,69510,66742,56032,54154,53083,62284,53673,60568.0,NaN
31,Immigrants,Foreigners,Asia,Western Asia,4181,4662,4120,2440,2882,3430,...,13728,15494,14541,13644,14719,15726,18503,16799,12477.0,NaN
32,Immigrants,Foreigners,Asia Total,NaN,31025,34314,30214,24696,27274,23850,...,134850,159253,149054,133459,139894,141434,163845,146894,152218.0,NaN
33,Immigrants,Foreigners,Europe,Eastern Europe,1467,3698,6873,5459,4433,3969,...,18360,16724,14389,13886,11988,11759,11803,9612,9464.0,NaN
34,Immigrants,Foreigners,Europe,Northern Europe,23721,26608,22134,10725,10845,10212,...,8486,8153,7969,9186,10042,9846,9816,7285,7616.0,NaN
35,Immigrants,Foreigners,Europe,Southern Europe,7762,7037,5222,3083,3033,2868,...,3200,2806,2417,2290,2692,2948,2661,2466,2854.0,NaN
36,Immigrants,Foreigners,Europe,Western Europe,6810,7459,8491,5371,3976,3795,...,8036,8272,8278,8133,9970,10525,9145,7415,9243.0,NaN
37,Immigrants,Foreigners,Europe Total,NaN,39760,44802,42720,24638,22287,20844,...,38082,35955,33053,33495,34692,35078,33425,26778,29177.0,NaN
38,Immigrants,Foreigners,Latin America and the Caribbean,Caribbean,7045,8310,8326,6998,5553,6048,...,6630,6816,6652,7826,8862,8847,10549,11958,11898.0,NaN
39,Immigrants,Foreigners,Latin America and the Caribbean,Central America,734,921,1612,3648,4087,4862,...,3346,3990,4140,5039,4891,4814,5692,5821,6019.0,NaN
40,Immigrants,Foreigners,Latin America and the Caribbean,South America,5302,5984,6831,4781,4038,4261,...,12205,13941,13884,13146,12794,13206,12577,10077,9256.0,NaN
41,Immigrants,Foreigners,Latin America and the Caribbean Total,NaN,13081,15215,16769,15427,13678,15171,...,22181,24747,24676,26011,26547,26867,28818,27856,27173.0,NaN
42,Immigrants,Foreigners,Northern America,Northern America,9378,10030,9074,7100,6661,6543,...,6990,8394,9613,9463,10190,8995,8142,7676,7891.0,NaN
43,Immigrants,Foreigners,Oceania,Australia and New Zealand,1304,1119,848,457,481,467,...,1280,1279,1193,1383,1498,1538,1423,1226,1399.0,NaN
44,Immigrants,Foreigners,Oceania,Melanesia,632,707,816,558,391,448,...,497,300,278,304,331,313,401,316,273.0,NaN
45,Immigrants,Foreigners,Oceania,Micronesia,1,..,..,1,..,..,...,1,2,1,3,1,2,..,..,2.0,NaN
46,Immigrants,Foreigners,Oceania,Polynesia,5,13,11,2,6,5,...,10,4,1,3,4,7,10,6,5.0,NaN
47,Immigrants,Foreigners,Oceania Total,NaN,1942,1839,1675,1018,878,920,...,1788,1585,1473,1693,1834,1860,1834,1548,1679.0,NaN
48,Immigrants,Foreigners,Unknown,Unknown,44000,18078,16904,13635,14855,14368,...,3739,4785,4583,4348,4197,3402,3731,2554,1681.0,NaN

In [5]:
#5
#Mengunduh dataset
df_unggah.to_csv('df_unggah.csv') # apabila menggunakan VS Code / Jupyter Notebook (Hanya sampai sini)
files.download('df_unggah.csv')

In [6]:
#6
#Menampilkan gambaran data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9994 non-null   int64
 1   order_id       9994 non-null   object
 2   order_date     9994 non-null   object
 3   ship_date      9994 non-null   object
 4   ship_mode      9994 non-null   object
 5   customer_id    9994 non-null   object
 6   customer_name  9994 non-null   object
 7   segment        9994 non-null   object
 8   country        9994 non-null   object
 9   city           9994 non-null   object
 10  state          9994 non-null   object
 11  postal_code    9994 non-null   int64
 12  region         9994 non-null   object
 13  product_id     9994 non-null   object
 14  category       9994 non-null   object
 15  subcategory    9994 non-null   object
 16  product_name   9994 non-null   object
 17  sales          9994 non-null   float64
 18  quantity       9994 non-null   int64
 19  discount       9994 non-null   float64
 20  profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

## Pengelolaan Data `Date`

In [7]:
#7
#Mengubah tipe kolom Date menjadi Datetime
df['order_date']= pd.to_datetime(df['order_date'])
df['ship_date']= pd.to_datetime(df['ship_date'])
df.dtypes

row_id                    int64
order_id                 object
order_date       datetime64[ns]
ship_date        datetime64[ns]
ship_mode                object
customer_id              object
customer_name            object
segment                  object
country                  object
city                     object
state                    object
postal_code               int64
region                   object
product_id               object
category                 object
subcategory              object
product_name             object
sales                   float64
quantity                  int64
discount                float64
profit                  float64
dtype: object

In [8]:
#8
#Membuat kolom tambahan untuk day, month, month_num
df['day']=df['order_date'].dt.day_name()
df['month']=df['order_date'].dt.month_name()
df['month_num']=df['order_date'].dt.month
df['year']=df['order_date'].dt.year
df['ship_delay'] = df['ship_date']-df['order_date'] #tipe datetime
df['ship_delay'] = df['ship_delay'].dt.days #konversi ke hari
df.head(5)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,product_name,sales,quantity,discount,profit,day,month,month_num,year,ship_delay
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,Tuesday,November,11,2016,3
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,Tuesday,November,11,2016,3
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,Sunday,June,6,2016,4
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,Sunday,October,10,2015,7
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,Sunday,October,10,2015,7

In [9]:
#9
#Latihan: Filter berdasarkan bulan October tahun 2015
df_oct = df[(df['month_num'] == 10) & (df['year'] == 2015)]
df_oct

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,product_name,sales,quantity,discount,profit,day,month,month_num,year,ship_delay
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,Sunday,October,10,2015,7
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,Sunday,October,10,2015,7
109,110,CA-2015-129476,2015-10-15,2015-10-20,Standard Class,PA-19060,Pete Armstrong,Home Office,United States,Orland Park,...,Logitech Gaming G510s - Keyboard,339.9600,5,0.20,67.9920,Thursday,October,10,2015,5
189,190,CA-2015-102281,2015-10-12,2015-10-14,First Class,MP-17470,Mark Packer,Home Office,United States,New York City,...,"Atlantic Metals Mobile 4-Shelf Bookcases, Cust...",899.1360,4,0.20,112.3920,Monday,October,10,2015,2
190,191,CA-2015-102281,2015-10-12,2015-10-14,First Class,MP-17470,Mark Packer,Home Office,United States,New York City,...,I Need's 3d Hello Kitty Hybrid Silicone Case C...,71.7600,6,0.00,20.0928,Monday,October,10,2015,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9416,9416,CA-2015-127824,2015-10-18,2015-10-22,Standard Class,JC-15775,John Castell,Consumer,United States,Seattle,...,Xerox 1903,17.9400,3,0.00,8.7906,Sunday,October,10,2015,4
9417,9417,CA-2015-127824,2015-10-18,2015-10-22,Standard Class,JC-15775,John Castell,Consumer,United States,Seattle,...,Eldon 100 Class Desk Accessories,10.1100,3,0.00,3.2352,Sunday,October,10,2015,4
9489,9489,CA-2015-156566,2015-10-01,2015-10-04,First Class,EM-13960,Eric Murdock,Consumer,United States,Portland,...,Wilson Electronics DB Pro Signal Booster,572.8000,2,0.20,50.1200,Thursday,October,10,2015,3
9912,9913,CA-2015-132388,2015-10-10,2015-10-12,First Class,KN-16390,Katherine Nockton,Corporate,United States,Santa Barbara,...,"Global Leather & Oak Executive Chair, Burgundy",362.1360,3,0.20,-54.3204,Saturday,October,10,2015,2
9913,9914,CA-2015-132388,2015-10-10,2015-10-12,First Class,KN-16390,Katherine Nockton,Corporate,United States,Santa Barbara,...,Avery 503,31.0500,3,0.00,14.9040,Saturday,October,10,2015,2

##Penggunaan fungsi `pivot_table` & `groupby`

### `pivot_table`

**Formula:**

nama_variable  =  `pd.pivot_table`(nama_dataframe`, values=`['kolom_nilai']`,index=`['baris']`,columns=`['header']`,aggfunc=np.`jenis_agregasi)

Output: `DataFrame`

In [10]:
#10
df_pivot = pd.pivot_table(df,values=['quantity'],index=['region'],columns=['category'],aggfunc=np.average)
df_pivot

          quantity
category Furniture Office Supplies Technology
region
Central   3.798337        3.803797   3.676190
East      3.683860        3.774533   3.629907
South     3.888554        3.819095   3.815700
West      3.813296        3.813917   3.898164

In [11]:
#11
#Buatlah tabel pivot untuk: index = country, header/kolom = city, nilainya = penjumlahan dari profit
df_pivot = pd.pivot_table(df,values=['profit'],index=['country'],columns=['city'],aggfunc=np.sum)
df_pivot

<ipython-input-11-dc483f3478cd>:3: FutureWarning: The provided callable <function sum at 0x7dc7de7000d0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df_pivot = pd.pivot_table(df,values=['profit'],index=['country'],columns=['city'],aggfunc=np.sum)

                profit                                                    \
city          Aberdeen Abilene     Akron Albuquerque Alexandria    Allen
country
United States     6.63 -3.7584 -186.6356    634.0881   318.6183 -39.8775

                                                      ...                     \
city          Allentown Altoona  Amarillo    Anaheim  ... Wilmington  Wilson
country                                               ...
United States -226.4504 -1.1835 -387.9683  1234.0036  ...  1947.7019 -14.336

                                                                            \
city           Woodbury Woodland Woodstock Woonsocket    Yonkers      York
country
United States  196.0962  33.3848   79.9929    78.6791  2767.7557 -102.1692


city          Yucaipa      Yuma
country
United States  13.208 -465.9909

[1 rows x 531 columns]

### `groupby`

**Formula:**

nama variabel = nama_dataframe`.groupby(by=`['kolom_1'  ,   'kolom_2'])['kolom_agregasi']`.`jenis_agregasi()

Output: `series`

In [12]:
#12
df_groupby = df.groupby(by=["month_num","month"])["profit"].sum()
df_groupby

month_num  month
1          January       9134.4461
2          February     10294.6107
3          March        28594.6872
4          April        11587.4363
5          May          22411.3078
6          June         21285.7954
7          July         13832.6648
8          August       21776.9384
9          September    36857.4753
10         October      31784.0413
11         November     35468.4265
12         December     43369.1919
Name: profit, dtype: float64

In [13]:
#13
#merubah output groupby menjadi DataFrame dengan as_index = False
df_groupby = df.groupby(by=["city","profit"], as_index=False)["profit"].sum()
df_groupby

          city    profit
0     Aberdeen    6.6300
1      Abilene   -3.7584
2        Akron  -80.9955
3        Akron  -75.8304
4        Akron  -56.3108
...        ...       ...
9688   Yucaipa   13.2080
9689      Yuma -479.9880
9690      Yuma  -35.8848
9691      Yuma    1.1808
9692      Yuma   48.7011

[9693 rows x 2 columns]

In [14]:
#14
#Buatlah dengan fungsi groupby, top 5 city penghasil profit paling besar.
df_groupby2 = df.groupby(by=["city"], as_index=False)["profit"].sum().sort_values(by='profit', ascending=False).head(5)
df_groupby2

              city      profit
329  New York City  62036.9837
266    Los Angeles  30440.7579
452        Seattle  29156.0967
438  San Francisco  17507.3854
123        Detroit  13181.7908

##Membuat dan menggunakan fungsi sederhana pada DataFrame

Formula:

`def` nama_fungsi `(`nilai`):`

    kondisi

In [15]:
#15
#Membuat suatu fungsi
def condition(value):
    if value > 2:
      return 'High'
    elif value == 2:
      return 'Medium'
    else:
        return 'Low'

In [16]:
#16
#Pengaplikasian fungsi
df['status'] = df['quantity'].apply(condition)
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,sales,quantity,discount,profit,day,month,month_num,year,ship_delay,status
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,Tuesday,November,11,2016,3,Medium
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,Tuesday,November,11,2016,3,High
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,Sunday,June,6,2016,4,Medium
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,Sunday,October,10,2015,7,High
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,Sunday,October,10,2015,7,Medium

In [17]:
#17
#Buatlah suatu kolom baru yang bernama delay_status yang dapat menyatakan bahwa apabila waktu pengiriman <= 4 hari dari tanggal order maka 'Good' selain itu maka 'Bad'
def condition1(value):
    if value <= 4:
      return 'Good'
    else:
        return 'Bad'
df['delay_status'] = df['ship_delay'].apply(condition1)
df.head(5)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,quantity,discount,profit,day,month,month_num,year,ship_delay,status,delay_status
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,2,0.00,41.9136,Tuesday,November,11,2016,3,Medium,Good
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,3,0.00,219.5820,Tuesday,November,11,2016,3,High,Good
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,2,0.00,6.8714,Sunday,June,6,2016,4,Medium,Good
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,5,0.45,-383.0310,Sunday,October,10,2015,7,High,Bad
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,2,0.20,2.5164,Sunday,October,10,2015,7,Medium,Bad

## Membuat visualisasi secara sederhana dengan menggunakan `plot`

In [18]:
#18
#Membuat grafik
df_groupby.plot(x='month',
           y=['profit'],
           kind='bar',
           grid = True,
           xlabel = 'Month',
           ylabel = 'Total Profit',
           figsize=(12,7),
           rot = 0, #Rotasi
           title = 'Monthly Total Profit',
           table = False,
#sort_columns = False,
           secondary_y = False)

KeyError: 'month'

## Menjalankan SQL di Colab dengan `sqlite3`

In [ ]:
#19
#Menjalankan SQL di Colab
from sqlite3 import connect
conn = connect(':memory:')
df.to_sql('tokopaedi',conn, index=False, if_exists='replace')

In [ ]:
#20
#Query SQL
df_sql = pd.read_sql("""
SELECT
    tokopaedi.city,
    sum(tokopaedi.profit) profit
from
    tokopaedi
group by
    1
order by
    2 desc
limit 10
""", conn)
df_sql

In [ ]:
#21
#Buat top 5 city berdasarkan sales pada bulan November 2016 dengan menggunakan sql
df_sql1 = pd.read_sql("""
SELECT
  tokopaedi.city,
  sum(tokopaedi.profit) profit
from
    tokopaedi
    where
    tokopaedi.month_num = 11 and
    tokopaedi.year = 2016
group by
    1
order by
    2 desc
limit 5
    """,conn)
df_sql1

#Minitask

Tampilkan TOP 5 City selama 2016 dengan berdasarkan nilai profit yang paling tinggi. Tampilkan juga dengan bar diagram.

Berikut contoh pengerjaan data yang lain: https://drive.google.com/drive/folders/1panwFfAKVaMzguX1jxxn0bkHaNE5IJFB?usp=sharing

In [ ]:
#22 Buat top 5 city berdasarkan profit pada tahun 2016 dengan menggunakan sql
df_sql2 = pd.read_sql("""
SELECT
    tokopaedi.city,
    sum(tokopaedi.profit) profit
from
    tokopaedi
    where
    tokopaedi.year = 2016
group by
     1
order by
      2 desc
limit 5
""", conn)
df_sql2

In [ ]:
#23 Membuat grafik
df_sql2.plot(x='city',
           y=['profit'],
           kind='bar',
           grid = True,
           xlabel = 'city',
           ylabel = 'Total Profit',
           figsize=(12,7),
           rot = 0, #Rotasi
           title = 'Top 5 City by Profit',
           table = False,
#sort_columns = False,
           secondary_y = False)